src/app/patients/edit-patient/edit-patient.page.html
src/app/patients/new-patient/new-patient.page.html

Removed minlength restriction in fields and cleaned up a bit of code.

:bug: Fix: Remove minlength in new patient and edit patient page

---

src/app/planning/services/planning-api.service.ts
src/app/planning/specific-planning/specific-planning.module.ts
src/app/planning/specific-planning/specific-planning.page.html
src/app/planning/specific-planning/specific-planning.page.ts
src/app/shared/components/dialogs/dialogs.component.html
src/app/shared/components/dialogs/dialogs.component.ts
src/app/shared/shared.module.ts

Added button for cancelling a planning in the specific planning page.

:sparkles: Feat: Add delete planning button

---

src/app/patients/specific-patient/specific-patient.page.ts

Es posible jugar un TFT mientras se verifica

:bug: Fix (delete-patient): Delete patient now unlinks it

---

src/app/patients/specific-patient/specific-patient.page.html
src/app/patients/specific-patient/specific-patient.page.ts
src/app/shared/components/dialogs/dialogs.component.ts

Algun dia indentare como la gente

:bug: Fix (delete-patient): delete patient now unlinks form backend

---

src/app/planning/new-planning/new-planning.page.html

:bug: Fix (Param): toggles remember states

---

src/app/planning/new-planning/new-planning.page.html
src/app/planning/new-planning/new-planning.page.ts

:bug: Fix (Param): one spriteset is always selected

---

src/app/patients/patients/patients.page.html
src/app/patients/patients/patients.page.scss
src/app/patients/patients/patients.page.ts
src/app/patients/shared-patients/services/patients-api/patients-api.service.ts

No me tocan a mi por que yo las estoy lanzando ndeah

:sparkles: Feat (patient-filter): added patient filter to patients page

---

src/app/patients/patients/patients.page.html

UNA SOLA LINEA Y 20 MINUTOS POR CASE SENSITIVE

:art: Style (no-results-message): added no results found message

---

src/app/patients/patients/patients.page.ts
src/app/patients/shared-patients/services/patients-api/patients-api.service.ts
src/app/planning/new-planning/new-planning.page.ts

Todo es terrible cuando se sortean PRs

:sparkles: Feat (active-patient-filter): redirected endpoints to filter

---

src/app/planning/new-planning/new-planning.page.html
src/app/planning/specific-planning/specific-planning.page.html

:sparkles: Feat (param-unit-display): param now shows unit used

---

src/app/patients/edit-patient/edit-patient.page.html
src/app/patients/edit-patient/edit-patient.page.ts
src/app/patients/new-patient/new-patient.page.html
src/app/patients/new-patient/new-patient.page.ts
src/app/planning/new-planning/new-planning.page.html
src/app/planning/new-planning/new-planning.page.ts
src/app/planning/specific-planning/specific-planning.page.html
src/app/planning/specific-planning/specific-planning.page.ts

Feat: submit/edit buttons now disable while awaiting answer

submit button on-hold

---

src/app/planning/specific-planning/specific-planning.page.ts

:bug: Fix (correct-button-enabling): moved button enabling

---

package-lock.json
package.json
src/app/patients/patients/patients-page.module.ts
src/app/patients/patients/patients.page.html
src/app/patients/patients/patients.page.ts

:sparkles: Feat (skeleton-loader): Added loader on Mis Pacientes

---

src/app/planning/planning.page.ts
src/app/planning/specific-planning/specific-planning.page.html

Badges agregadas + error de navegacion de filtros de busqueda

:sparkles: Feat (planning-badges): added badges + small filter fix

---

package.json

Solo se cambio version a test-0.17.0, dominio ya correctamente asignado

:sparkles: Feat (version-change): changed version, no IPs modified

---

src/app/planning/planning.page.html

:sparkles: Feat (no-results-message): reworked no result message trigger

---

src/app/patients/patients/patients.page.html

:sparkles: Feat (no-patients-message): reworked no result message

---

src/app/planning/shared-planning/components/game-session-results/game-session-results.component.ts
src/app/planning/specific-planning/specific-planning.page.html
src/app/planning/specific-planning/specific-planning.page.ts
src/app/shared/components/result-card/result-card.component.scss
src/app/shared/components/table/table.component.ts

:bug: Fix (App): Fix table adding extra page, card size not matching

---

src/app/patients/specific-patient/specific-patient.page.ts

:bug: Fix (specific-patient): remove unlink modal

---

src/app/patients/specific-patient/specific-patient.module.ts
src/app/patients/specific-patient/specific-patient.page.html
src/app/patients/specific-patient/specific-patient.page.scss
src/app/patients/specific-patient/specific-patient.page.ts
src/app/shared/components/result-card/result-card.component.html
src/app/shared/components/result-card/result-card.component.scss
src/app/shared/pipes/custom-date.pipe.ts

:sparkles: Feat (specific-patient): add recent results

---

src/app/patients/specific-patient/specific-patient.page.html
src/app/patients/specific-patient/specific-patient.page.ts

:sparkles: Feat (specific-patient): added ongoing plannings
